# Generated by Django 3.0.5 on 2020-04-11 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('title', models.CharField(blank=True, default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AboutPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('caption', models.CharField(blank=True, default=None, max_length=200)),
                ('name', models.CharField(blank=True, default=None, max_length=100)),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='date and time posted')),
            ],
        ),
        migrations.CreateModel(
            name='HomePagePhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='homepage/')),
                ('caption', models.CharField(blank=True, default=None, max_length=200)),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='date and time posted')),
                ('name', models.CharField(blank=True, default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PhotographyPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='photography/')),
                ('caption', models.CharField(blank=True, default=None, max_length=200)),
                ('category', models.CharField(choices=[('a', 'Weddings'), ('b', 'Fill-In'), ('c', 'Models'), ('d', 'Cars'), ('e', 'Events'), ('f', 'Landscapes'), ('g', 'Portraits'), ('h', 'Visual Communication'), ('i', 'Product Design')], default='Weddings', max_length=2)),
                ('name', models.CharField(blank=True, default=None, max_length=100)),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='date and time posted')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioBio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personalImage', models.ImageField(blank=True, null=True, upload_to='portfolio/')),
                ('bio', models.TextField()),
                ('age', models.CharField(blank=True, default=None, max_length=10)),
                ('location', models.CharField(blank=True, default=None, max_length=50)),
                ('name', models.CharField(blank=True, default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('a', 'Education'), ('b', 'Experience')], default='Education', max_length=2)),
                ('year_start', models.CharField(blank=True, default=None, max_length=10)),
                ('year_end', models.CharField(blank=True, default=None, max_length=10)),
                ('name', models.CharField(blank=True, default=None, max_length=150)),
                ('position', models.CharField(blank=True, default=None, max_length=150)),
                ('description', models.TextField()),
            ],
        ),
    ]
