# Generated by Django 3.0.5 on 2020-04-11 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('body', models.TextField()),
                ('title', models.CharField(blank=True, default=None, max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='AboutDescription',
        ),
        migrations.DeleteModel(
            name='AboutPhoto',
        ),
        migrations.DeleteModel(
            name='PortfolioBio',
        ),
        migrations.RemoveField(
            model_name='homepagephoto',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='photographyphoto',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='photographyphoto',
            name='date',
        ),
        migrations.AddField(
            model_name='photographyphoto',
            name='cover',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='portfolioentry',
            name='location',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='photographyphoto',
            name='category',
            field=models.CharField(choices=[('Weddings', 'Weddings'), ('Cars', 'Cars'), ('Models', 'Models'), ('Events', 'Events'), ('Landscapes', 'Landscapes'), ('Visual Communication', 'Visual Communication'), ('Product Design', 'Product Design'), ('Portraits', 'Portraits'), ('Nature', 'Nature')], default='Weddings', max_length=25),
        ),
        migrations.AlterField(
            model_name='portfolioentry',
            name='category',
            field=models.CharField(choices=[('Education', 'Education'), ('Experience', 'Experience')], default='Education', max_length=25),
        ),
        migrations.AlterField(
            model_name='portfolioentry',
            name='position',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
    ]
