# Generated by Django 3.0.1 on 2020-04-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_manager', '0002_auto_20200411_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographyphoto',
            name='category',
            field=models.CharField(choices=[('Ocean', 'Ocean'), ('Gadgets', 'Gadgets'), ('Sky', 'Sky'), ('Wildlife', 'Wildlife'), ('Portraits', 'Portraits'), ('Urban', 'Urban'), ('Product Design', 'Product Design'), ('Forest', 'Forest'), ('Flower', 'Flower')], default='Ocean', max_length=25),
        ),
    ]
